name: Run lint

on: [push, pull_request]

jobs:
  linter:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install linter
        run: |
          python3 -m pip install ruff
      - name: Lint
        run: |
          make lint
